name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone `waallet-contract`
        uses: actions/checkout@v4
        with:
          repository: 'pilagod/waallet-contract'
          path: 'waallet-contract'
          submodules: recursive

      # - name: Expose GitHub runtime
      #   uses: crazy-max/ghaction-github-runtime@v3

      # - name: Clone `rundler`
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'alchemyplatform/rundler'
      #     path: 'waallet-contract/vendor/rundler'
      #     submodules: recursive

      # - name: Set up Docker buildx 
      #   uses: docker/setup-buildx-action@v3

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: ${{ runner.os }}-buildx-

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: './waallet-contract/vender/rundler'
      #     load: true
      #     tags: rundler
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # - name: Cache register
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
      #
      # - name: Build Docker image
      #   uses: docker/build-push-action@v5
      #   working-directory: 'waallet-contract'
      #   with:
      #     context: vendor/rundler
      #     builder: ${{ steps.buildx.outputs.name }}
      #     load: true
      #     tags: rundler
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache

      # - name: Build `rundler` 
      #   working-directory: 'waallet-contract'
      #   run: docker buildx build vendor/rundler -t rundler
      
      # - name: Build `rundler` 
      #   working-directory: 'waallet-contract'
      #   run: docker buildx build vendor/rundler -t rundler --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Spin up testnet
        working-directory: 'waallet-contract'
        run: docker compose -f ./docker/testnet/docker-compose-node.yml up --build -d

      - name: Wait for testnet initialized
        run: sleep 10s
        shell: bash

      - name: Set up testnet
        working-directory: 'waallet-contract'
        run: docker compose -f ./docker/testnet/docker-compose-node-setup.yml up --build

      - name: Use Node.js v16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Clone `waallet-extension`
        uses: actions/checkout@v4
        with:
          repository: 'pilagod/waallet-extension'
          path: 'waallet-extension'

      - name: Set up `waallet-extension` 
        working-directory: 'waallet-extension'
        run: npm ci

      - name: Run tests
        working-directory: 'waallet-extension'
        run: npm run test

      # # Temp fix
      # # https://github.com/docker/build-push-action/issues/252
      # # https://github.com/moby/buildkit/issues/1896
      # - name: Refresh Docker cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
